hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}


batch_size: 4
accum_iter: 8
lr: 5e-5
num_epoch: 20
length: 512
p: 0 # subword regularization hyperparameter p in train step 
seed: 42
device: "cuda"
model_name: "roberta-base" # bert-large-cased roberta-large

weight_decay: 0.01
use_loss_weight: False
use_scheduler: True
warmup_rate: 0.1

post_sentence_padding: True
add_sep_between_sentences: True

load_local_model: False
test_model_name: "4ldk/Roberta-Base-CoNLL2003"
test: "test" # valid, test, 2023, crossweigh

loop: 1 # the number of test loops
pred_p: 0.1 # subword regularization hyperparameter p in test step

huggingface_cache: False # "D:/huggingface/cashe"
visible_devices: False # "0" 